fix: Change lower version of redis, connect-redis due to error
ConnectionTimeoutError: Connection timeout
at Socket.<annoymous> (...\node_modules\@redis\client...)